# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader = "javafml"
loaderVersion = "${loader_version_range}"

license = "${mod_license}"
issueTrackerURL = "https://github.com/GamingEinstein/CardCraft/issues"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
#updateJSONURL=""
displayURL = "https://modrinth.com/mod/CardCraft"
logoFile="cardcraft_logo.png"
credits = "Buddycards, for inspiring this mod!"
authors = "${mod_authors}"
#displayTest="MATCH_VERSION"
description = '''${mod_description}'''
itemIcon = "cardcraft:base_trading_card"

[[dependencies.${mod_id}]]
modId = "forge"
mandatory = true
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependecies.${mod_id}]]
modId = "midnightlib"
mandatory = true
versionRange = "[1.0,)"
ordering = "AFTER"
side = "BOTH"

#[features.${mod_id}]
#openGLVersion="[3.2,)"